### ISSUE TITLE
Site Map / UML Diagrams

### ISSUE THREAD

**Issue by bshepley** [COMP3340-SuperSet/documentation#4]
https://www.lucidchart.com/pages/

**Comment by Ru-Two** [comment]
For site map: https://lucid.app/lucidchart/invitations/accept/inv_94f21ff5-1ce7-4490-8145-d4a92bc3f56e?viewport_loc=-11%2C-11%2C2219%2C1159%2C0_0

**Comment by bshepley** [comment]
Added an updated site map to the bottom of the lucid chart doc.
